# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Next.js Static Site

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    if: ${{secrets.SITE_ID}} != '' && ${{ secrets.NETLIFY_KEY }} != ''
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - run: npm install
    - run: npm run build 
    - run: npm run export
    - uses: netlify/actions/cli@master
      with:
          args: deploy --dir=out
      env:
        NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_KEY }}
